# Generated by Django 6.0.6 on 2026-07-15 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('nome_exibicao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BancoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('multipla_escolha', 'Múltipla Escolha'), ('completar_frase', 'Completar Frase'), ('vocabulario', 'Vocabulário'), ('classificacao', 'Classificação')], max_length=30)),
                ('enunciado', models.TextField()),
                ('resposta_correta', models.CharField(max_length=200)),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroJogada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(default='multiplicacao', max_length=50)),
                ('nivel', models.CharField(default='unidades', max_length=50)),
                ('numero_1', models.IntegerField(default=0)),
                ('numero_2', models.IntegerField(default=0)),
                ('resposta_aluno', models.CharField(default='0', max_length=200)),
                ('acertou', models.BooleanField()),
                ('tempo_segundos', models.FloatField()),
                ('data_jogada', models.DateTimeField(auto_now_add=True)),
                ('jogador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
