# Generated by Django 6.0.6 on 2026-06-03 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroJogada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_1', models.IntegerField()),
                ('numero_2', models.IntegerField()),
                ('resposta_aluno', models.IntegerField()),
                ('acertou', models.BooleanField()),
                ('tempo_segundos', models.FloatField()),
                ('data_jogada', models.DateTimeField(auto_now_add=True)),
                ('jogador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
