# Generated by Django 6.0.6 on 2026-06-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrojogada',
            name='nivel',
            field=models.CharField(default='unidades', max_length=20),
        ),
        migrations.AddField(
            model_name='registrojogada',
            name='operacao',
            field=models.CharField(default='multiplicacao', max_length=20),
        ),
    ]
